/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.sonicraft;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class SonicraftModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public SonicraftModElements() {
		sounds.put(new ResourceLocation("sonicraft", "mob.sonicidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonicidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.sonichurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonichurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.sonicdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonicdie")));
		sounds.put(new ResourceLocation("sonicraft", "ring.collect"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "ring.collect")));
		sounds.put(new ResourceLocation("sonicraft", "spring.use"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "spring.use")));
		sounds.put(new ResourceLocation("sonicraft", "starpost.use"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "starpost.use")));
		sounds.put(new ResourceLocation("sonicraft", "mob.sonicroll"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonicroll")));
		sounds.put(new ResourceLocation("sonicraft", "ring.loss"), new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "ring.loss")));
		sounds.put(new ResourceLocation("sonicraft", "music.invincibility"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.invincibility")));
		sounds.put(new ResourceLocation("sonicraft", "monitor.destroy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "monitor.destroy")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailsidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailsidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailshurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailshurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailsdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailsdie")));
		sounds.put(new ResourceLocation("sonicraft", "mob.knucklesidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.knucklesidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.knuckleshurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.knuckleshurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.knucklesdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.knucklesdie")));
		sounds.put(new ResourceLocation("sonicraft", "sonic.1up"), new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "sonic.1up")));
		sounds.put(new ResourceLocation("sonicraft", "shield.trigger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "shield.trigger")));
		sounds.put(new ResourceLocation("sonicraft", "super.transform"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "super.transform")));
		sounds.put(new ResourceLocation("sonicraft", "generic.charge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "generic.charge")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmanidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmanidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmanhit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmanhit")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmanshoot"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmanshoot")));
		sounds.put(new ResourceLocation("sonicraft", "signpost.spin"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "signpost.spin")));
		sounds.put(new ResourceLocation("sonicraft", "chemical.change"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "chemical.change")));
		sounds.put(new ResourceLocation("sonicraft", "chemical.bounce"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "chemical.bounce")));
		sounds.put(new ResourceLocation("sonicraft", "chaosemerald.collect"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "chaosemerald.collect")));
		sounds.put(new ResourceLocation("sonicraft", "mobius.portal.activate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mobius.portal.activate")));
		sounds.put(new ResourceLocation("sonicraft", "mobius.dimension.enter"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mobius.dimension.enter")));
		sounds.put(new ResourceLocation("sonicraft", "mobius.dimension.exit"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mobius.dimension.exit")));
		sounds.put(new ResourceLocation("sonicraft", "mob.amyidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.amyidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.amyhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.amyhurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.amydie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.amydie")));
		sounds.put(new ResourceLocation("sonicraft", "mob.shadowidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.shadowidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.shadowhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.shadowhurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.shadowdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.shadowdie")));
		sounds.put(new ResourceLocation("sonicraft", "mob.shadow.eggman"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.shadow.eggman")));
		sounds.put(new ResourceLocation("sonicraft", "mob.shadowprovoked"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.shadowprovoked")));
		sounds.put(new ResourceLocation("sonicraft", "mob.sonicthanks"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonicthanks")));
		sounds.put(new ResourceLocation("sonicraft", "pikopikohammer.attack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "pikopikohammer.attack")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailsfly"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailsfly")));
		sounds.put(new ResourceLocation("sonicraft", "mob.metalsonicidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.metalsonicidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.metalsonichurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.metalsonichurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.metalsonicdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.metalsonicdie")));
		sounds.put(new ResourceLocation("sonicraft", "mileselectric.open"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mileselectric.open")));
		sounds.put(new ResourceLocation("sonicraft", "mob.cyclonetarget"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.cyclonetarget")));
		sounds.put(new ResourceLocation("sonicraft", "mob.cyclonestep"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.cyclonestep")));
		sounds.put(new ResourceLocation("sonicraft", "mob.cyclonejump"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.cyclonejump")));
		sounds.put(new ResourceLocation("sonicraft", "mob.cyclonelaser"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.cyclonelaser")));
		sounds.put(new ResourceLocation("sonicraft", "mob.cyclonehurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.cyclonehurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailscyclonedefeat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailscyclonedefeat")));
		sounds.put(new ResourceLocation("sonicraft", "mob.tailscyclonehurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.tailscyclonehurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.sonicjump"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.sonicjump")));
		sounds.put(new ResourceLocation("sonicraft", "mob.rougeidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.rougeidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.rougehurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.rougehurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.rougedie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.rougedie")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.greenhill"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.greenhill")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.chemicalplant"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.chemicalplant")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.marble"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.marble")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmandefeat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmandefeat")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmanpinch"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmanpinch")));
		sounds.put(new ResourceLocation("sonicraft", "mob.chaoidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.chaoidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.chaohurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.chaohurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.chaodie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.chaodie")));
		sounds.put(new ResourceLocation("sonicraft", "action.fail"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "action.fail")));
		sounds.put(new ResourceLocation("sonicraft", "mob.infiniteidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.infiniteidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.infinitehurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.infinitehurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.infinitedefeat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.infinitedefeat")));
		sounds.put(new ResourceLocation("sonicraft", "phantomruby.activate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "phantomruby.activate")));
		sounds.put(new ResourceLocation("sonicraft", "phantomruby.action"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "phantomruby.action")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.nullspace"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.nullspace")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.nullspace.additions"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.nullspace.additions")));
		sounds.put(new ResourceLocation("sonicraft", "infinite.summon"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "infinite.summon")));
		sounds.put(new ResourceLocation("sonicraft", "bumper.use"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "bumper.use")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.springyard"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.springyard")));
		sounds.put(new ResourceLocation("sonicraft", "airbubble.breathe"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "airbubble.breathe")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.aquaticruin"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.aquaticruin")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.scrapbrain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.scrapbrain")));
		sounds.put(new ResourceLocation("sonicraft", "slotmachine.active"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "slotmachine.active")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.casinonight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.casinonight")));
		sounds.put(new ResourceLocation("sonicraft", "mob.deatheggrobotstomp"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.deatheggrobotstomp")));
		sounds.put(new ResourceLocation("sonicraft", "mob.chargeeffectidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.chargeeffectidle")));
		sounds.put(new ResourceLocation("sonicraft", "machine.activate"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "machine.activate")));
		sounds.put(new ResourceLocation("sonicraft", "mob.deatheggrobot.defeat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.deatheggrobot.defeat")));
		sounds.put(new ResourceLocation("sonicraft", "mob.eggmanretreat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.eggmanretreat")));
		sounds.put(new ResourceLocation("sonicraft", "blastprocessing.primed"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "blastprocessing.primed")));
		sounds.put(new ResourceLocation("sonicraft", "spike.hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "spike.hurt")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.starlight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.starlight")));
		sounds.put(new ResourceLocation("sonicraft", "camera.snap"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "camera.snap")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.studiopolis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.studiopolis")));
		sounds.put(new ResourceLocation("sonicraft", "music.game.emeraldhill"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "music.game.emeraldhill")));
		sounds.put(new ResourceLocation("sonicraft", "mob.creamidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.creamidle")));
		sounds.put(new ResourceLocation("sonicraft", "mob.creamhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.creamhurt")));
		sounds.put(new ResourceLocation("sonicraft", "mob.creamdie"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("sonicraft", "mob.creamdie")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("sonicraft").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == SonicraftModElements.ModElement.class)
						elements.add((SonicraftModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(SonicraftModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new SonicraftModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		SonicraftMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final SonicraftModElements elements;
		protected final int sortid;
		public ModElement(SonicraftModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
